name: run auto_sst

on:
  workflow_dispatch:
    inputs:
      build_image:
        description: 'build the docker image as part of the workflow?'
        required: true
        default: 'true'
        type: boolean
  schedule: 
    - cron: '0 04 * * *' # 0600 SAST

jobs:
  build_image:
    if: ${{ github.event.inputs.build_image == 'true' }}  # Conditional execution (saves time when testing something else and we don't want to build it every time)
    uses: ./.github/workflows/build_image.yml  # Path to your reusable workflow

  # Set the environment variables 
  envs:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_REF: ${{ steps.BRANCH_REF.outputs.value }}
    steps:
      - name: Set the BRANCH_REF
        id: BRANCH_REF
        run: |
          echo "value=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

  run-script:
    needs: [envs,build_image]
    if: ${{ always() }}  # Always run even if build_image is not executed (but it'll wait for build_image if it is)
    runs-on: ubuntu-latest
    env:
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
    steps:
      - name: run the script
        run: >-
          docker run \
            --rm \
            -v ${{ github.workspace }}:/tmp \
            ghcr.io/saeon/auto_sst_${{ env.BRANCH_REF }}:latest \
              ${{ secrets.COPERNICUS_USERNAME }} \
              ${{ secrets.COPERNICUS_PASSWORD }} \
              ${{ secrets.EMAIL_SENDER }} \
              ${{ secrets.EMAIL_PASSWORD }}

